name: 'Run EC2 Command via AWS SSM'
description: 'Run remote bash commands on EC2 using AWS SSM without SSH or keys.'
author: 'Thomas Joseph'
branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  instance-id:
    description: 'EC2 instance ID'
    required: true
  region:
    description: 'AWS region'
    required: true
  commands:
    description: 'Multiline bash commands to run remotely'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run remote command via SSM
      shell: bash
      run: |
        echo "Verifying inputs..."
        echo "Region: $INPUT_REGION"
        echo "Instance ID: $INPUT_INSTANCE_ID"

        if [ -z "$INPUT_REGION" ]; then
          echo "❌ Region is empty. Aborting."
          exit 1
        fi

        if ! command -v jq >/dev/null 2>&1; then
          echo "jq not found, installing..."
          sudo apt-get update && sudo apt-get install -y jq
        fi

        echo "Converting commands to JSON array..."
        COMMANDS_JSON=$(echo "$INPUT_COMMANDS" | jq -R -s -c 'split("\n") | map(select(length > 0))')

        echo "Sending SSM command to $INPUT_INSTANCE_ID..."
        COMMAND_ID=$(aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=instanceids,Values=$INPUT_INSTANCE_ID" \
          --parameters "{\"commands\":$COMMANDS_JSON}" \
          --region "$INPUT_REGION" \
          --query "Command.CommandId" \
          --output text)

        echo "Waiting for command to complete (ID: $COMMAND_ID)..."
        aws ssm wait command-executed \
          --region "$INPUT_REGION" \
          --command-id "$COMMAND_ID" \
          --targets "Key=instanceids,Values=$INPUT_INSTANCE_ID"

        echo "Fetching command output..."
        aws ssm get-command-invocation \
          --command-id "$COMMAND_ID" \
          --instance-id "$INPUT_INSTANCE_ID" \
          --region "$INPUT_REGION"